# Site settings
title: DALI 2018 - Data Learning and Inference
permalink: "/:categories/:title.html"
# Include image banner file name below
banner: 

# Registration fees and URL go here.
registration:
  fee:
    academic: 400 euros
    industry: 500 euros
  url:

# Hotel booking URL goes here
booking:
  url:
  
conference:
  draft: true
  hide_tentative: true
  hosts:
  general:
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: Amazon and University of Sheffield
  - name: Bernhard Schölkopf
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI for Intelligent Systems Tübingen
  workshop:
  - given: Sebastian
    family: Nowozin
    institute: Microsoft Research Cambridge
    url: "http://www.nowozin.net/sebastian/"
  symposium:
  - given: Fernando
    family: Perez-Cruz
    url: "https://web.stevens.edu/facultyprofile/?id=2224"
    institute: "Stevens Institute of Technology"
  - name: Isabel Valera
    url: "http://www.mpi-sws.org/~ivalera/"
    institute: "Max Planck Institute for Software Systems"
  assistants:
  - name: Sabrina Nepozitek
    url: "http://www.da.inf.ethz.ch/people/SabrinaNepozitek/"
    institute: ETH Zurich
  steering:
  - name: Zoubin Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  - name: Thomas Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: Amazon and University of Sheffield
  - name: Bernhard Schölkopf (chair)
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI Tübingen
  name: DALI 2018 - Data Learning and Inference
  shortname: DALI
  venue: H10 Rubicón Palace
  location: Playa Blanca, Lanzarote, Canary Islands
  year: 2018
  month: April
  dates:
  - 2018-04-03
  - 2018-04-04
  - 2018-04-05
  sponsors:
  - name: Max-Planck-ETH Center for Learning Systems
    url: "http://learning-systems.org/"
previous_meeting:
  name: DALI 2017
  url: "http://dalimeeting.org/dali2017/"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.org" # the base hostname & protocol for your site
youtube:
  height: 315
  width: 560
twitter_username: 
github_username:  dalimeeting
github:
  edit: true
  repository: dalimeeting.github.io
future: true

# Build settings
markdown: kramdown
