# Site settings
title: DALI 2016 - Data Learning and Inference
venue: Sestri Levante, Italy
permalink: "/:categories/:title.html"
conference:
  hosts:
  organizers:
  - name: Zoubin Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  - name: Thomas Hoffman
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: University of Sheffield
  - name: Lorenzo Rosasco
    url: "http://web.mit.edu/lrosasco/www/"
    institute: University of Genova and MIT
  - name: Bernhard Schölkopf
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI Tübingen
  name: DALI 2016 - Data Learning and Inference
  location: Sestri Levante, Italy
  year: 2016
  month: March
  dates:
  - {date: 30, day: Friday, month: March, year: 2016}
  - {date: 31, day: Saturday, month: March, year: 2016}
  - {date: 1, day: Sunday, month: April, year: 2016}
  draft: True # set to True if the programme is draft only.
  sponsors:
  - name: Max-Planck-ETH Center for Learning Systems
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  dalimeeting

# Build settings
markdown: kramdown
