# Site settings
title: DALI 2017 - Data Learning and Inference
venue: H10 Costa Adeje Palace, Tenerife, Canary Islands
permalink: "/:categories/:title.html"
banner: # banner to appear here.
conference:
  hosts:
  general:
  - name: Thomas Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  workshop:
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: University of Sheffield
  symposium:
  - name: Zoubin Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  local:
  - name: Lorenzo Rosasco
    url: "http://web.mit.edu/lrosasco/www/"
    institute: University of Genova and MIT
  assistants:
  - name: Pablo Olmos
    url: "http://www.tsc.uc3m.es/~olmos/"
    institute: " Universidad Carlos III de Madrid"
  - name: Sabrina Nepozitek
    url: "http://www.da.inf.ethz.ch/people/SabrinaNepozitek/"
    institute: ETH Zurich
  steering:
  - name: Zoubin Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  - name: Thomas Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: Amazon and University of Sheffield
  - name: Bernhard Schölkopf (chair)
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI Tübingen
  name: DALI 2017 - Data Learning and Inference
  location: H10 Costa Adeje Palace, Tenerife, Canary Islands
  year: 2017
  month: April
  dates:
  - 2017-04-18
  - 2017-04-19
  - 2017-04-20
  draft: False # set to True if the programme is draft only.
  sponsors:
  - name: Max-Planck-ETH Center for Learning Systems
    url: "http://learning-systems.org/"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.org" # the base hostname & protocol for your site
youtube:
  height: 315
  width: 560
twitter_username: 
github_username:  dalimeeting
future: true

# Build settings
markdown: kramdown
